engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      ignore_warnings: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
ratings:
  paths:
  - "**.js"
exclude_paths:
- "**/node_modules"
