engines:
  duplication:
    enabled: true
    exclude_paths:
    - "**/env/**/webpack.config.js"
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  markdownlint:
      enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
ratings:
  paths:
  - "**.js"
  - "**.md"
exclude_paths:
- "**/node_modules"
- "**/.git"
- "**/.idea"
- "**/test-output-files"
